serverAddr = "62.234.218.25"
serverPort = 7000

includes = ["/etc/frp/frpc.d/*.toml"]

[auth]
token="38324"

[log]
level="info"
maxDays=3


[transport]
tls.enable=true

[[proxies]]
name="ssh"
type="tcp"
localIP="127.0.0.1"
localPort=22
remotePort=6001
